swagger: '2.0'
info:
  description: >-
    This is Resource Manager API which used with WSO2 Stream Processor
    distributed deployment.
  version: v1
  title: SP Resource Manager
  contact:
    name: WSO2
    url: 'http://wso2.com/analytics'
    email: architecture@wso2.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: localhost
basePath: /resourceManager
tags:
  - name: ResourceManager
    description: >-
      ResourceManager will keep track of the resource pool. This can be used to
      add resources to the resource pool.
schemes:
  - https
  - http
paths:
  /resourceManager/heartbeat:
    post:
      tags:
        - ResourceManager
      summary: Register resource node and Updates Heartbeat.
      description: >-
        Resource nodes will call this endpoint to get them self registerd in the
        resource pool. Once registered, consecetive calls for this endpoints
        will be used as heartbeat from tose resource nodes.
      operationId: updateHeartbeat
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: >-
            Node object that needs to be registered or update heartbeats as the
            resource.
          required: true
          schema:
            $ref: '#/definitions/Node'
      responses:
        '200':
          description: Resource successfully added / Heartbeat updated.
          schema:
            $ref: '#/definitions/ManagerNode'
        '301':
          description: Not the current leader (redir to correct leader).
          schema:
            $ref: '#/definitions/ManagerNode'
        '405':
          description: Invalid input
  /resourceManager/deployment:
    get:
      tags:
        - ResourceManager
      summary: Get the satus.
      description: Returns status of manager nodes cluster and the resourcepool.
      operationId: getStatus
      produces:
        - application/json
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/Deployment'
definitions:
  Node:
    description: Representation of a Node which consists of a host and a port
    properties:
      id:
        type: string
      host:
        type: string
      port:
        type: integer
    required:
      - id
      - host
      - port
  ManagerNode:
    description: Representation of a Manager Node
    allOf:
      - $ref: '#/definitions/Node'
      - properties:
          isLeader:
            type: boolean
            default: false
          heartbeatInterval:
            type: integer
            format: int64
        required:
          - isLeader
          - heartbeatInterval
  Deployment:
    description: Deployment details of the managers and the resource pool
    properties:
      managers:
        description: list of Manager Nodes
        type: array
        items:
          $ref: '#/definitions/ManagerNode'
      resources:
        description: Nodes in the resource pool
        type: array
        items:
          $ref: '#/definitions/Node'
    required:
      - managers
      - resources
